<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>Ant-contrib Tasks: Throw</title>
  </head>

  <body>
    <h1>Throw</h1>

    <p>Extension of Ant's built-in <code>&lt;fail&gt;</code> task that
    can throw an exception that is given by a reference.  This may be
    useful if you want to rethrow the exception that has been caught
    by a <code>&lt;trycatch&gt;</code> task in the
    <code>&lt;catch&gt;</code> block.</p>

    <h2>Parameters</h2>
    <table border="1" cellpadding="2" cellspacing="0">
      <tr>
        <th>Attribute</th>
        <th>Description</th>
        <th>Required</th>
      </tr>
      <tr>
        <td valign="top">refid</td>
        <td valign="top">Id of the referenced exception.</td>
        <td align="center" valign="top">No.</td>
      </tr>
    </table>

    <p>In addition, all attributes of the <a
    href="http://jakarta.apache.org/ant/manual/CoreTasks/fail.html"><code>&lt;fail&gt;</code>
    task</a> are supported.</p>

    <hr>
    <p align="center">Copyright &copy; 2002 Ant-Contrib Project. All
    rights Reserved.</p>

  </body>
</html>
